{% set name = "econ-ark" %}
{% set version = "0.10.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f15bfd3a1a423f175cfaaabcb415f83182c844553cd9b6bfd45c816c8a242923

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3,<3.8

  run:
    - python >=3,<3.8
    - dill
    - joblib
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - HARK
    - HARK.tests

about:
  home: https://github.com/econ-ark/HARK
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Heterogenous Agents Resources & toolKit

extra:
  recipe-maintainers:
    - MridulS
    - shaunagm
    - sbenthall

