{% set name = "econ-ark" %}
{% set version = "0.10.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9563d8e62cde22bf849de046ed1f7717e6820fa80ed09ca62ef52e63ab90124f

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3,<3.8
    - numpy
    - scipy
  
  run:
    - python >=3,<3.8
    - dill
    - joblib
    - matplotlib
    - numpy
    - scipy

test:
  imports:
    - HARK
    - HARK.tests

about:
  home: https://github.com/econ-ark/HARK
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: Heterogenous Agents Resources & toolKit

extra:
  recipe-maintainers:
    - MridulS
    - shaunagm
