{% set name = "econ-ark" %}
{% set version = "0.10.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e528c003e0ae2c70661ed2f0d1288b4b87414e6ecae387b7e5ecbc9048746bb

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3,<3.8
  
  run:
    - python >=3,<3.8
    - dill
    - joblib
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - HARK
    - HARK.tests

about:
  home: https://github.com/econ-ark/HARK
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Heterogenous Agents Resources & toolKit

extra:
  recipe-maintainers:
    - MridulS
    - shaunagm
    - sbenthall

