travis:
  secure:
    BINSTAR_TOKEN: jl/v6HulzRypeG9RuqPd/mTnwe/IIoib7T5271n6pvRpzXtUqT9EQgH3XQlXn4RC6ZfjaYF07CCW0F1akXmj+xwTDIJBsW5Zf+3DjKS+ekFjqhYyhvXTBdix0KV3UAPU8975ZQ3fh52hkgwV1CJPA4eXvTOIOiwbxHqpr4T1zlAc773i4bXIfEKWrMvJAy+xlz65BRUC9IkvO4UXHWDdfu0Ztec8PgSwono95yRxR1K67iooLFyFLyreYYE3tPtqIXqIlOyA/mW3gLepA3J5Xa3a1tustt04Xrd5TLCaZ4rplsW/9iL67+OzXedGiSckxQpTtE1/RhmunGUXBI3d9M0Fcfi+3tkV3BmsXHkgn/sfjj3tEa9hgOJZmrdw2AQuSdlEkp9c9jWEgiJ7cR/kFu7uQo7MalghnIbP47YY+SfTsAzfmPAdXwUwHd6yz2H67EjPPyG9LEsshf8UVZXokHXSkX304+8fyowgFy1fi3kYeFT9hcGbW1i4XtG6/1CnDJ3hsXg/GzxCbI9mc1dm3xquQBxwq2rLry7TJHcJ/FoDzHB/5a6fNC0/VPsKMUh1wyQswuto8dfMcnh3xnkKTrJk/RwnwB8srkGR7dihkRI9AHsyY0GG5GJC5rz6kKBRIf1KODWI2nF2IoewYdhJyj7hJ5/mkiv3ZFojtOvKpSA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
